In [1]:
import pandas as pd

# Load the dataset
file_path = '/content/drive/MyDrive/climate-ds.csv'  # Replace with the actual path to your file
data = pd.read_csv(file_path)

# Display basic information about the dataset
print(data.info())

# Display the first few rows of the dataset
print(data.head())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Unnamed: 0                     28242 non-null  int64  
 1   Area                           28242 non-null  object 
 2   Item                           28242 non-null  object 
 3   Year                           28242 non-null  int64  
 4   average_rain_fall_mm_per_year  28242 non-null  int64  
 5   pesticides_tonnes              28242 non-null  float64
 6   avg_temp                       28242 non-null  float64
 7   hg/ha_yield                    28242 non-null  int64  
dtypes: float64(2), int64(4), object(2)
memory usage: 1.7+ MB
None
   Unnamed: 0     Area         Item  Year  average_rain_fall_mm_per_year  \
0           0  Albania        Maize  1990                           1485   
1           1  Albania     Potatoes  1990                           1485 

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_percentage_error
import numpy as np

# Selecting one attribute and the target variable
X = data[['average_rain_fall_mm_per_year']]
y = data['hg/ha_yield']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Training the linear regression model
reg = LinearRegression().fit(X_train, y_train)

# Making predictions on the training set
y_train_pred = reg.predict(X_train)

# Making predictions on the testing set
y_test_pred = reg.predict(X_test)


In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error, r2_score
import numpy as np

# Selecting one attribute
X = data[['average_rain_fall_mm_per_year']]
y = data['hg/ha_yield']

# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Training the Linear Regression model
reg = LinearRegression().fit(X_train, y_train)

# Making predictions on the train and test sets
y_train_pred = reg.predict(X_train)
y_test_pred = reg.predict(X_test)

# Calculating metrics for the train set
mse_train = mean_squared_error(y_train, y_train_pred)
rmse_train = np.sqrt(mse_train)
mape_train = mean_absolute_percentage_error(y_train, y_train_pred)
r2_train = r2_score(y_train, y_train_pred)

# Calculating metrics for the test set
mse_test = mean_squared_error(y_test, y_test_pred)
rmse_test = np.sqrt(mse_test)
mape_test = mean_absolute_percentage_error(y_test, y_test_pred)
r2_test = r2_score(y_test, y_test_pred)

print("Train MSE:", mse_train)
print("Train RMSE:", rmse_train)
print("Train MAPE:", mape_train)
print("Train R2:", r2_train)

print("Test MSE:", mse_test)
print("Test RMSE:", rmse_test)
print("Test MAPE:", mape_test)
print("Test R2:", r2_test)


Train MSE: 7133355744.744209
Train RMSE: 84459.19573820372
Train MAPE: 2.7597954376806784
Train R2: 5.819665521400452e-05
Test MSE: 7414555975.03856
Test RMSE: 86107.81599273413
Test MAPE: 2.574483986729407
Test R2: -0.0003249768605686487


In [5]:
# Calculating metrics for the training set
mse_train = mean_squared_error(y_train, y_train_pred)
rmse_train = np.sqrt(mse_train)
mape_train = mean_absolute_percentage_error(y_train, y_train_pred)
r2_train = r2_score(y_train, y_train_pred)

# Calculating metrics for the testing set
mse_test = mean_squared_error(y_test, y_test_pred)
rmse_test = np.sqrt(mse_test)
mape_test = mean_absolute_percentage_error(y_test, y_test_pred)
r2_test = r2_score(y_test, y_test_pred)

print(f"Training Set Metrics:\nMSE: {mse_train}, RMSE: {rmse_train}, MAPE: {mape_train}, R2: {r2_train}")
print(f"Testing Set Metrics:\nMSE: {mse_test}, RMSE: {rmse_test}, MAPE: {mape_test}, R2: {r2_test}")


Training Set Metrics:
MSE: 7133355744.744209, RMSE: 84459.19573820372, MAPE: 2.7597954376806784, R2: 5.819665521400452e-05
Testing Set Metrics:
MSE: 7414555975.03856, RMSE: 86107.81599273413, MAPE: 2.574483986729407, R2: -0.0003249768605686487


In [9]:
# Selecting multiple attributes for the model
X_multi = data[['average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp']]
y_multi = data['hg/ha_yield']

# Splitting the data into train and test sets
X_train_multi, X_test_multi, y_train_multi, y_test_multi = train_test_split(X_multi, y_multi, test_size=0.3, random_state=42)

# Training the Linear Regression model
reg_multi = LinearRegression().fit(X_train_multi, y_train_multi)

# Making predictions on the train and test sets
y_train_pred_multi = reg_multi.predict(X_train_multi)
y_test_pred_multi = reg_multi.predict(X_test_multi)

# Calculating metrics for the train set
mse_train_multi = mean_squared_error(y_train_multi, y_train_pred_multi)
rmse_train_multi = np.sqrt(mse_train_multi)
mape_train_multi = mean_absolute_percentage_error(y_train_multi, y_train_pred_multi)
r2_train_multi = r2_score(y_train_multi, y_train_pred_multi)

# Calculating metrics for the test set
mse_test_multi = mean_squared_error(y_test_multi, y_test_pred_multi)
rmse_test_multi = np.sqrt(mse_test_multi)
mape_test_multi = mean_absolute_percentage_error(y_test_multi, y_test_pred_multi)
r2_test_multi = r2_score(y_test_multi, y_test_pred_multi)

print("Train MSE:", mse_train_multi)
print("Train RMSE:", rmse_train_multi)
print("Train MAPE:", mape_train_multi)
print("Train R2:", r2_train_multi)

print("Test MSE:", mse_test_multi)
print("Test RMSE:", rmse_test_multi)
print("Test MAPE:", mape_test_multi)
print("Test R2:", r2_test_multi)


Train MSE: 7009667241.82564
Train RMSE: 83723.75554062084
Train MAPE: 2.708184358812498
Train R2: 0.017396642834985654
Test MSE: 7259787159.482684
Test RMSE: 85204.3846259257
Test MAPE: 2.5053767208118645
Test R2: 0.020555452441047617


In [7]:
from sklearn.cluster import KMeans

# Selecting features for clustering (excluding the target variable)
X = data[['average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp']]

# Performing k-means clustering
kmeans = KMeans(n_clusters=2, random_state=0, n_init="auto").fit(X)

# Cluster labels and cluster centers
labels = kmeans.labels_
centers = kmeans.cluster_centers_

print(f"Cluster Labels:\n{labels}")
print(f"Cluster Centers:\n{centers}")


Cluster Labels:
[0 0 0 ... 0 0 0]
Cluster Centers:
[[1.12714029e+03 2.72951239e+04 2.04653595e+01]
 [1.74239165e+03 3.01904651e+05 2.26345229e+01]]
